/**
 * Export Utilities
 * Handle exporting projection sessions to various formats
 */

import type { ProjectionSession } from '../types';

/**
 * Export session as Markdown
 */
export function exportSessionAsMarkdown(session: ProjectionSession): string {
  const { scenario, messages, createdAt } = session;

  let markdown = `# ${scenario.title}\n\n`;
  markdown += `**Scenario Type:** ${scenario.type}\n`;
  markdown += `**Created:** ${new Date(createdAt).toLocaleString()}\n`;
  markdown += `**Messages:** ${messages.length}\n\n`;

  if (scenario.context) {
    markdown += `## Context\n\n${scenario.context}\n\n`;
  }

  markdown += `---\n\n`;
  markdown += `## Conversation\n\n`;

  messages.forEach((message) => {
    const speaker = message.role === 'user' ? 'You' : scenario.participantRole;
    const timestamp = new Date(message.timestamp).toLocaleTimeString();

    markdown += `### ${speaker} (${timestamp})\n\n`;
    markdown += `${message.content}\n\n`;
  });

  markdown += `---\n\n`;
  markdown += `*Generated by The Great Work Suite - Projection*\n`;

  return markdown;
}

/**
 * Export session as JSON
 */
export function exportSessionAsJSON(session: ProjectionSession): string {
  return JSON.stringify(session, null, 2);
}

/**
 * Export session as plain text
 */
export function exportSessionAsText(session: ProjectionSession): string {
  const { scenario, messages, createdAt } = session;

  let text = `${scenario.title.toUpperCase()}\n`;
  text += `${'='.repeat(scenario.title.length)}\n\n`;
  text += `Scenario Type: ${scenario.type}\n`;
  text += `Created: ${new Date(createdAt).toLocaleString()}\n`;
  text += `Messages: ${messages.length}\n\n`;

  if (scenario.context) {
    text += `Context:\n${scenario.context}\n\n`;
  }

  text += `${'-'.repeat(60)}\n\n`;
  text += `CONVERSATION:\n\n`;

  messages.forEach((message) => {
    const speaker = message.role === 'user' ? 'YOU' : scenario.participantRole.toUpperCase();
    const timestamp = new Date(message.timestamp).toLocaleTimeString();

    text += `[${timestamp}] ${speaker}:\n`;
    text += `${message.content}\n\n`;
  });

  text += `${'-'.repeat(60)}\n\n`;
  text += `Generated by The Great Work Suite - Projection\n`;

  return text;
}

/**
 * Download content as file
 */
export function downloadFile(content: string, filename: string, mimeType: string): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = sanitizeFilename(filename);
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Copy to clipboard
 */
export async function copyToClipboard(text: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch (error) {
    console.error('Failed to copy to clipboard:', error);
    return false;
  }
}

/**
 * Sanitize filename for download
 */
function sanitizeFilename(filename: string): string {
  return filename
    .replace(/[^a-z0-9_\-\.]/gi, '_')
    .replace(/_+/g, '_')
    .substring(0, 100);
}
