/**
 * Portfolio Export Utilities
 * Handle exporting portfolios to various formats
 */

import type { Portfolio, Achievement } from '../types';
import { CATEGORY_INFO, STATUS_INFO } from '../constants';

/**
 * Export portfolio as Markdown
 */
export function exportPortfolioAsMarkdown(portfolio: Portfolio): string {
  const { title, description, achievements } = portfolio;

  let markdown = `# ${title}\n\n`;
  markdown += `${description}\n\n`;
  markdown += `---\n\n`;

  // Group by category
  const categories = [...new Set(achievements.map((a) => a.category))];

  categories.forEach((category) => {
    const categoryAchievements = achievements.filter((a) => a.category === category);
    if (categoryAchievements.length === 0) return;

    const categoryInfo = CATEGORY_INFO[category];
    markdown += `## ${categoryInfo.icon} ${categoryInfo.label}\n\n`;

    categoryAchievements.forEach((achievement) => {
      markdown += formatAchievementMarkdown(achievement);
      markdown += `\n`;
    });
  });

  markdown += `---\n\n`;
  markdown += `*Generated by The Great Work Suite - Culmination*\n`;

  return markdown;
}

/**
 * Format single achievement as markdown
 */
function formatAchievementMarkdown(achievement: Achievement): string {
  const statusInfo = STATUS_INFO[achievement.status];

  let md = `### ${statusInfo.icon} ${achievement.title}\n\n`;
  md += `**Status:** ${statusInfo.label}\n`;
  md += `**Target Date:** ${new Date(achievement.targetDate).toLocaleDateString()}\n`;

  if (achievement.completionDate) {
    md += `**Completed:** ${new Date(achievement.completionDate).toLocaleDateString()}\n`;
  }

  if (achievement.tags.length > 0) {
    md += `**Tags:** ${achievement.tags.map((t) => `#${t}`).join(' ')}\n`;
  }

  md += `\n${achievement.description}\n`;

  if (achievement.metrics && achievement.metrics.length > 0) {
    md += `\n**Key Metrics:**\n\n`;
    achievement.metrics.forEach((metric) => {
      md += `- ${metric.icon || '•'} **${metric.label}:** ${metric.value}\n`;
    });
  }

  if (achievement.narrative) {
    md += `\n**Success Story:**\n\n${achievement.narrative}\n`;
  }

  return md;
}

/**
 * Export portfolio as JSON
 */
export function exportPortfolioAsJSON(portfolio: Portfolio): string {
  return JSON.stringify(portfolio, null, 2);
}

/**
 * Export portfolio as HTML
 */
export function exportPortfolioAsHTML(portfolio: Portfolio): string {
  const { title, description, achievements, theme } = portfolio;

  let html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(title)}</title>
  <style>
    ${getPortfolioCSS(theme)}
  </style>
</head>
<body class="theme-${theme}">
  <div class="portfolio-container">
    <header class="portfolio-header">
      <h1>${escapeHtml(title)}</h1>
      <p class="portfolio-description">${escapeHtml(description)}</p>
    </header>

    <main class="achievements-grid">
`;

  achievements.forEach((achievement) => {
    html += formatAchievementHTML(achievement);
  });

  html += `
    </main>

    <footer class="portfolio-footer">
      <p>Generated by The Great Work Suite - Culmination</p>
      <p>${new Date().toLocaleDateString()}</p>
    </footer>
  </div>
</body>
</html>`;

  return html;
}

/**
 * Format single achievement as HTML card
 */
function formatAchievementHTML(achievement: Achievement): string {
  const categoryInfo = CATEGORY_INFO[achievement.category];
  const statusInfo = STATUS_INFO[achievement.status];

  return `
    <div class="achievement-card" data-category="${achievement.category}" data-status="${achievement.status}">
      <div class="achievement-header">
        <span class="achievement-category">${categoryInfo.icon} ${categoryInfo.label}</span>
        <span class="achievement-status status-${achievement.status}">${statusInfo.icon} ${statusInfo.label}</span>
      </div>

      <h2 class="achievement-title">${escapeHtml(achievement.title)}</h2>

      <p class="achievement-description">${escapeHtml(achievement.description)}</p>

      ${achievement.imageUrl ? `<img src="${escapeHtml(achievement.imageUrl)}" alt="${escapeHtml(achievement.title)}" class="achievement-image" />` : ''}

      ${achievement.metrics && achievement.metrics.length > 0 ? `
        <div class="achievement-metrics">
          ${achievement.metrics.map((m) => `
            <div class="metric">
              <span class="metric-icon">${m.icon || '•'}</span>
              <span class="metric-label">${escapeHtml(m.label)}</span>
              <span class="metric-value">${escapeHtml(m.value)}</span>
            </div>
          `).join('')}
        </div>
      ` : ''}

      ${achievement.tags.length > 0 ? `
        <div class="achievement-tags">
          ${achievement.tags.map((tag) => `<span class="tag">#${escapeHtml(tag)}</span>`).join('')}
        </div>
      ` : ''}

      <div class="achievement-dates">
        <span>Target: ${new Date(achievement.targetDate).toLocaleDateString()}</span>
        ${achievement.completionDate ? `<span>Completed: ${new Date(achievement.completionDate).toLocaleDateString()}</span>` : ''}
      </div>

      ${achievement.narrative ? `
        <details class="achievement-narrative">
          <summary>Success Story</summary>
          <p>${escapeHtml(achievement.narrative)}</p>
        </details>
      ` : ''}
    </div>
  `;
}

/**
 * Get CSS for portfolio HTML export
 */
function getPortfolioCSS(_theme: Portfolio['theme']): string {
  return `
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }

    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      line-height: 1.6;
      color: #333;
      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
      padding: 2rem;
    }

    .portfolio-container {
      max-width: 1200px;
      margin: 0 auto;
      background: white;
      border-radius: 16px;
      box-shadow: 0 20px 60px rgba(0, 0, 0, 0.3);
      overflow: hidden;
    }

    .portfolio-header {
      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
      color: white;
      padding: 3rem 2rem;
      text-align: center;
    }

    .portfolio-header h1 {
      font-size: 3rem;
      margin-bottom: 1rem;
      font-weight: 700;
    }

    .portfolio-description {
      font-size: 1.25rem;
      opacity: 0.95;
    }

    .achievements-grid {
      display: grid;
      grid-template-columns: repeat(auto-fill, minmax(350px, 1fr));
      gap: 2rem;
      padding: 2rem;
    }

    .achievement-card {
      background: white;
      border: 1px solid #e5e7eb;
      border-radius: 12px;
      padding: 1.5rem;
      transition: transform 0.2s, box-shadow 0.2s;
    }

    .achievement-card:hover {
      transform: translateY(-4px);
      box-shadow: 0 12px 24px rgba(0, 0, 0, 0.1);
    }

    .achievement-header {
      display: flex;
      justify-content: space-between;
      align-items: center;
      margin-bottom: 1rem;
      font-size: 0.875rem;
    }

    .achievement-category {
      background: #f3f4f6;
      padding: 0.25rem 0.75rem;
      border-radius: 9999px;
      font-weight: 500;
    }

    .achievement-status {
      padding: 0.25rem 0.75rem;
      border-radius: 9999px;
      font-weight: 500;
    }

    .status-envisioned {
      background: #f3f4f6;
      color: #6b7280;
    }

    .status-in_progress {
      background: #dbeafe;
      color: #1e40af;
    }

    .status-achieved {
      background: #d1fae5;
      color: #065f46;
    }

    .achievement-title {
      font-size: 1.5rem;
      margin-bottom: 0.75rem;
      color: #111827;
    }

    .achievement-description {
      color: #6b7280;
      margin-bottom: 1rem;
    }

    .achievement-image {
      width: 100%;
      height: 200px;
      object-fit: cover;
      border-radius: 8px;
      margin-bottom: 1rem;
    }

    .achievement-metrics {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
      gap: 0.75rem;
      margin-bottom: 1rem;
    }

    .metric {
      background: #f9fafb;
      padding: 0.75rem;
      border-radius: 8px;
      display: flex;
      flex-direction: column;
      gap: 0.25rem;
    }

    .metric-icon {
      font-size: 1.5rem;
    }

    .metric-label {
      font-size: 0.75rem;
      color: #6b7280;
      text-transform: uppercase;
      letter-spacing: 0.05em;
    }

    .metric-value {
      font-size: 1.125rem;
      font-weight: 600;
      color: #111827;
    }

    .achievement-tags {
      display: flex;
      flex-wrap: wrap;
      gap: 0.5rem;
      margin-bottom: 1rem;
    }

    .tag {
      background: #ede9fe;
      color: #5b21b6;
      padding: 0.25rem 0.75rem;
      border-radius: 9999px;
      font-size: 0.875rem;
    }

    .achievement-dates {
      font-size: 0.875rem;
      color: #6b7280;
      display: flex;
      flex-direction: column;
      gap: 0.25rem;
      margin-bottom: 1rem;
    }

    .achievement-narrative {
      margin-top: 1rem;
      padding-top: 1rem;
      border-top: 1px solid #e5e7eb;
    }

    .achievement-narrative summary {
      cursor: pointer;
      font-weight: 600;
      color: #667eea;
      margin-bottom: 0.5rem;
    }

    .achievement-narrative p {
      color: #4b5563;
      line-height: 1.7;
    }

    .portfolio-footer {
      background: #f9fafb;
      padding: 2rem;
      text-align: center;
      color: #6b7280;
      font-size: 0.875rem;
    }

    @media (max-width: 768px) {
      .achievements-grid {
        grid-template-columns: 1fr;
      }

      .portfolio-header h1 {
        font-size: 2rem;
      }
    }
  `;
}

/**
 * Export portfolio as plain text
 */
export function exportPortfolioAsText(portfolio: Portfolio): string {
  const { title, description, achievements } = portfolio;

  let text = `${title.toUpperCase()}\n`;
  text += `${'='.repeat(title.length)}\n\n`;
  text += `${description}\n\n`;
  text += `${'-'.repeat(60)}\n\n`;

  achievements.forEach((achievement) => {
    const categoryInfo = CATEGORY_INFO[achievement.category];
    const statusInfo = STATUS_INFO[achievement.status];

    text += `${categoryInfo.icon} ${achievement.title}\n`;
    text += `Category: ${categoryInfo.label} | Status: ${statusInfo.label}\n`;
    text += `Target: ${new Date(achievement.targetDate).toLocaleDateString()}\n`;

    if (achievement.completionDate) {
      text += `Completed: ${new Date(achievement.completionDate).toLocaleDateString()}\n`;
    }

    text += `\n${achievement.description}\n`;

    if (achievement.metrics && achievement.metrics.length > 0) {
      text += `\nMetrics:\n`;
      achievement.metrics.forEach((metric) => {
        text += `  ${metric.icon || '•'} ${metric.label}: ${metric.value}\n`;
      });
    }

    if (achievement.tags.length > 0) {
      text += `\nTags: ${achievement.tags.map((t) => `#${t}`).join(' ')}\n`;
    }

    text += `\n${'-'.repeat(60)}\n\n`;
  });

  text += `Generated by The Great Work Suite - Culmination\n`;
  text += `${new Date().toLocaleDateString()}\n`;

  return text;
}

/**
 * Download content as file
 */
export function downloadFile(content: string, filename: string, mimeType: string): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = sanitizeFilename(filename);
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Copy to clipboard
 */
export async function copyToClipboard(text: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch (error) {
    console.error('Failed to copy to clipboard:', error);
    return false;
  }
}

/**
 * Sanitize filename for download
 */
function sanitizeFilename(filename: string): string {
  return filename
    .replace(/[^a-z0-9_\-\.]/gi, '_')
    .replace(/_+/g, '_')
    .substring(0, 100);
}

/**
 * Escape HTML special characters
 */
function escapeHtml(text: string): string {
  const div = document.createElement('div');
  div.textContent = text;
  return div.innerHTML;
}
